### ISSUE TITLE
Perl 6 Types:  list class subparts in order 

### ISSUE THREAD

**Issue by tbrowder** [perl6/user-experience#10]
When perusing Perl 6 docs at:

  https://doc.perl6.org/type.html

class parts such as routines and methods need to be in other than seemingly random order.  It is difficult to find a specific method or routine in such a list.

**Comment by awwaiid** [comment]
Do you mean the list of routines you get when you click in to a class page?

**Comment by tbrowder** [comment]
On Wed, Feb 10, 2016 at 3:15 PM, Brock Wilcox <notifications@github.com> wrote:
> Do you mean the list of routines you get when you click in to a class page?

Yes, sorry I didn't make that clear.

Thanks.

-Tom

**Comment by zoffixznet** [comment]
I opened an Issue for this on the docs repo: https://github.com/perl6/doc/issues/392

Thanks a lot for the report!
