### ISSUE TITLE
Shall we suggest Foo::Bar::X::What::Happened exception name format?

### ISSUE THREAD

**Issue by bbkr** [perl6/user-experience#11]
https://docs.perl6.org/type/Exception

There was discussion on IRC how exceptions should be defined in **_user modules**_.
Current documentation suggests `X::Foo::Bar::What::Happened` but `Foo::Bar::X::What::Happened` is better because:
- It is clear which part is the name of package and which is the name of exception. Let's take old `X::User::Access::Auth::Invalid` for example - did we have problem with accessing authorization system from `User` class or did we simply get wrong credentials in `User::Access` class? Defining this as `User::Access::X::Auth::Invalid` makes things explicit - we have separate class for user access and it got wrong credentials.
- It is lexically scoped - exception `What::Happened` can be defined in `Foo::Bar` class and exported.
- When ecosystem will grow we will encounter many conflicts in `X::` namespace. For example people will be defining exceptions like `X::ParamMissing` and use them in `Foo::Bar` class. Exception should be encapsulated. I know that there is `:auth` to distinguish package origin but it won't solve the problem.

So what is your opinion? Shall we promote in docs `Foo::Bar::X::What::Happened` format (and create issues in modules that use `X::` format to refactor them while ecosystem is still young) ?

**Comment by quietfanatic** [comment]
I agree with this and all its rationales.  Things defined by a module should all be in that module's namespace.

**Comment by AlexDaniel** [comment]
I didn't know this ticket existed, so I filed another one: https://github.com/perl6/user-experience/issues/11

This repo will likely be unified with problem-solving in the future, so I'm closing this ticket in favor of the other one.

**Comment by vrurg** [comment]
I think you meant perl6/problem-solving#57

**Comment by AlexDaniel** [comment]
Ah, yes! Thank you!
