### ISSUE TITLE
Create an online interpreter that can be embedded into online books / blogs

### ISSUE THREAD

**Issue by WildYorkies** [perl6/user-experience#15]
Similar to the interpreter/compiler system built into [Rust By Example](http://rustbyexample.com/hello/print.html)

This service could then be re-used by a number of tutorials / books.

**Comment by zoffixznet** [comment]
That already exists: [glot.io](https://glot.io)

Perl6.Party uses it. Click on any code example and you can modify/run it: http://perl6.party/post/Perl-6-S---Substitution-Operator

**Comment by WildYorkies** [comment]
Did you just embed the glot.io iframe in your blog? Under the share link? 

```<iframe src='https://glot.io/snippets/emfuaraio4/embed' frameborder='0' scrolling='no' sandbox='allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts' width='600' height='400'></iframe>``` 

for example ^

**Comment by zoffixznet** [comment]
That's another way of doing it, yes.

You can also use [Glot.IO's API](https://glot.io/api) too (we [got a module](https://github.com/zoffixznet/perl6-GlotIO)). Perl6.party just uses it under the hood to get execution results and [codemirror](https://codemirror.net/) for the frontend.
