### ISSUE TITLE
There are some Wikipedia articles on programming that need Perl6 examples

### ISSUE THREAD

**Issue by ijneb** [perl6/user-experience#28]
Here are all the ones I've found: https://pastecode.xyz/view/5a4e619d. I think it's important to have examples on wikipedia for potential new users scrolling through.

**Comment by shlomif** [comment]
I am copying these links here in case the contents of the paste gets removed:

* https://en.wikipedia.org/wiki/Exception_handling_syntax
* https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(associative_array)
* https://en.wikipedia.org/wiki/Anonymous_function#Examples
* https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(string_functions)
* https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)
* https://en.wikipedia.org/wiki/Constructor_(object-oriented_programming)

**Comment by lizmat** [comment]
Added example at: https://en.wikipedia.org/wiki/Constructor_(object-oriented_programming)

**Comment by lizmat** [comment]
Split Perl 5 section into a Perl 5 and a Perl 6 section on 	• https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)

**Comment by lizmat** [comment]
Added examples at 	• https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(string_functions)

**Comment by lizmat** [comment]
Added Perl 6 section to 	https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(associative_array)

**Comment by lizmat** [comment]
Exception handling is sufficiently different in Perl 6 that it doesn’t work to copy-paste the Perl 5 section and then just make changes.  So I will have to contemplate a bit on that one:
	• https://en.wikipedia.org/wiki/Exception_handling_syntaxD

**Comment by ijneb** [comment]
Thanks Liz!
