### ISSUE TITLE
Perl6 Website suggestion

### ISSUE THREAD

**Issue by RnBrgn** [perl6/user-experience#3]
When you click on the "Download" tab on the Perl6.org page,  I think it we be more straight forward and cleaner if we would see all the information, which is currently being shown at  http://rakudo.org/how-to-get-rakudo, ,,,, to be shown on the main download tab instead..

For a newbee/hobbyst programmer ( That's me ) or a newcomer to Perl and Perl 6 ( That's me )  , 
it feels a bit strange to be redirected to the compilers website. You think your about to download Perl6 and now your at Rakudo.org. 

I don't want to get into the "how things should be named" game.  But from what I see, there only seems to be one compiler for the Perl6 spec. Rakudo. Why can't that just be the default and not have to put Rakudo in front of Perl6  when it comes to downloading. Click here to download    "Perl6"
Have a default implementation.
Then have a section on the website called "Alternative Implementations of the Perl Spec"
JVM
.net
abc compiler

**Comment by zoffixznet** [comment]
Thank you. That is, indeed a problem, compounded by there not being yet a Rakudo Star distribution that ships with Christmas Perl 6 implementation. I'm hoping to have a "first draft" solution with [GetPerl6.com website](Getting-Perl6/README.md) this weekend that'll be aimed to give users "a Perl 6" without them having to learn about specs, compilers, and backends.

**Comment by WildYorkies** [comment]
Should this still be open?

**Comment by zoffixznet** [comment]
Don't think so....
