### ISSUE TITLE
Should tools support .t6 extension?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/user-experience#36]
See https://github.com/perl6/doc/issues/2576 for the previous discussion.

Affected tools and other things:

- [x] zef

- [x] App::Mi6

- [x] App::Assixt

- [ ] prove (no ticket)

- [x] prove6

- [x] travis

- [x] https://github.com/perl6/modules.perl6.org

Also:
- [ ] docs https://github.com/perl6/doc/issues/2576
- [ ] wikipedia?
- [ ] github linguist (no ticket)
- [ ] https://fileinfo.com/ ? Note that it already knows about `.p6`, but not about `.pl6` or `.pm6` (there's an entry for `.pm6` associating it with a discontinued product)

**Comment by jmaslak** [comment]
I'll submit a PR for Mi6 this evening.

**Comment by Leont** [comment]
> This also affects prove6.

An implementation of this is part of the `dev` branch :-)

**Comment by Leont** [comment]
App::Mi6 currently writes a `.travis.yml` that doesn't take this into account

**Comment by Leont** [comment]
> App::Mi6 currently writes a `.travis.yml` that doesn't take this into account

This has been fixed in https://github.com/skaji/mi6/commit/017c8dc43fa5b7a5e09d9cc7de7faeaa8661faad

**Comment by AlexDaniel** [comment]
This no longer matters.

**Comment by AlexDaniel** [comment]
Although, similar approach should be used for new extensions, but I believe creating a *new* ticket is a good idea.
