### ISSUE TITLE
Improve Perl 6 Download

### ISSUE THREAD

**Issue by moltar** [perl6/user-experience#7]
https://perl6.org/downloads/

The command instructions are understandable only to someone who is already involved in p6. If a person is a total newbie, then things like moar, panda and zef make no sense.

I think it needs to explain better what each command does and why is it needed.

**Comment by moltar** [comment]
Seems to be related to #4.

**Comment by zoffixznet** [comment]
Yeah, it's what #4 is about. I'm going to close this.

We're currently waiting for the Rakudo Star to be released, which is what the newbies would be directed to download, rather than build Perl 6 from source.
